class Towns: 

    BOWDON_HALE = 'BOWDON-HALE'
    HADFIELD_HOLLINGWORTH = 'HADFIELD-HOLLINGWORTH'
    HASHLINGTON = 'HASLINGTON'
    HYDE = 'HYDE'
    OUNDLE = 'OUNDLE'
    SKELMERSDALE = 'SKELMERSDALE'
    CARLTON = 'CARLTON-HARWORTH-TICKHILL'
    CRAWLEY = 'CRAWLEY'
    BAMFORD = 'BAMFORD-WHITWORTH'
    UPPINGHAM = 'UPPINGHAM'
    BRACKLEY = 'BRACKLEY' 
    LUTTERWORTH = 'LUTTERWORTH'



class SbCodes: 

    JOINT_CHAMBER_SB_12_CLIENTS = 'JOINT CHAMBER SB 12 CLIENTS'
    JOINT_CHAMBER_SB_MOS = 'JOINT CHAMBER SB MOS'
    JOINT_CHAMBER_SB_SAT = 'JOINT CHAMBER SB SAT'

    POLE_SB_24_CLIENTS = 'POLE SB 24 CLIENTS'
    POLE_SB_24_CLIENTS_MOS = 'POLE SB 24 CLIENTS MOS'
    POLE_SB_24_CLIENTS_SAT = 'POLE SB 24 CLIENTS SAT'


class JointBoxCodes : 

    JOINT_BOX_SMALL = 'JOINT BOX SMALL'
    JOINT_BOX_MEDIAN = 'JOINT BOX MEDIAN'
    JOINT_BOX_BIG = 'JOINT BOX BIG'


class CableCodes: 

    CABLE_12_FO = '12 f.o.'
    CABLE_12_FO_ULW = '12 f.o. ULW'
    
    CABLE_48_FO = '48 f.o.'
    CABLE_48_FO_ULW = '48 f.o. ULW'
